SOURCE=main.cpp system.cpp electrostaticpotential.cpp electricfield.cpp solve.cpp spectra.cpp plot.cpp ic.cpp display.cpp
CC=g++ -std=c++11
LDFLAGS=-I ~/Documents/boost_1_58_0
EXEC=./a.out

compilation:
	@ $(CC) $(SOURCE) $(LDFLAGS)  && $(EXEC)
