SOURCE=classical_motion_with_ODEINT_plot.cpp
#SOURCE=classical_motion_with_ODEINT.cpp
#SOURCE=oscillateur.cpp
CC=g++ -std=c++11
LDFLAGS=-I ~/Documents/boost_1_58_0
EXEC=./a.out

compilation:
	@ $(CC) $(SOURCE) $(LDFLAGS)  && $(EXEC)
